version: '3.8'

services:
  backend:
    build: ./server
    container_name: nestjs_app
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: angular_app
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge